### ISSUE TITLE
Update Guava version from 30.1.1-jre to 31.1-jre.

### ISSUE THREAD

**Issue by btkawaharahd** [terasolunaorg/terasoluna-gfw#1176]
## Description

After updating the Spring Boot version to 2.7.0, the following error occurs.

`Caused by: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableMap.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Lcom/google/common/collect/ImmutableMap;
`
## Possible Solution

Update Guava version from 30.1.1-jre to 31.1-jre.

## Affect versions

- 5.7.2.RELEASE

## Issue links
> Links to related issues.

- #1174
